#!/bin/sh

# -------------------------
# Swift files
# -------------------------
CHANGED_SWIFT_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep '\.swift$')

if [ -n "$CHANGED_SWIFT_FILES" ]; then
  echo "🔍 Found changed Swift files:"
  echo "$CHANGED_SWIFT_FILES"

  # Convert newline-separated list to space-separated list
  FILE_LIST=$(echo "$CHANGED_SWIFT_FILES" | tr '\n' ' ')

  echo "🛠  Running swift-format format..."
  swift-format format $FILE_LIST -i --configuration .swift-format

  echo "➕ Adding formatted Swift changes to commit..."
  echo "$CHANGED_SWIFT_FILES" | xargs git add

  echo "🔎 Running swift-format lint on changed files..."
  swift-format lint $FILE_LIST -s --configuration .swift-format

  if [ $? -ne 0 ]; then
    echo "❌ Swift lint check failed! Please fix the errors and try again."
    exit 1
  fi
else
  echo "ℹ️ No changed Swift files to check."
fi

exit 0
