name: Publish

on:
  push:
    tags:

jobs:
  publish:
    name: Publish
    environment: prod
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Run Lint Checks
        uses: ./.github/actions/lint-check

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          gh release create "$TAG" \
              --title "$TAG" \
              --verify-tag \
              --prerelease
        shell: bash