name: 'Swift format'
description: 'Run swift format checks'

runs:
  using: 'composite'
  steps:
    - name: Run swift format
      shell: bash
      run:  |
        xcrun swift-format lint \
        Sources/ TelegramLoginWidgetSample/ Package.swift  \
        --recursive  \
        -s \
        --configuration .swift-format